title: Jonas El Gammal
description: My Personal Webpage
baseurl: "" # Leave this empty for user.github.io sites

url: "https://jonaselgammal.github.io"

# Comment this out since you're using a local copy of the theme
# theme: minima
sass:
  style: compressed

# Optional: Remove this unless youâ€™re using a special layout that includes `page.css`
defaults:
  -
    scope:
      path: ""
    values:
      css: "assets/css/style.css"

social_links:
  - title: GitHub
    icon: github
    url: "https://github.com/jonaselgammal"
  - title: LinkedIn
    icon: linkedin
    url: "https://www.linkedin.com/in/jelgammal/"

plugins:
  - jekyll-feed

# Navigation links
header_pages:
  - research.md
  - resources.md
  - resume.md
